# Generated by Django 3.2.16 on 2022-10-31 00:12

from django.db import migrations, models
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('doogkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(default='default.svg', storage=storages.backends.azure_storage.AzureStorage, upload_to=''),
        ),
        migrations.AddField(
            model_name='housing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housing',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddConstraint(
            model_name='housing',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', -1), ('rating__lte', 5)), name='The rating value must be -1 (unrated) or an integer between 0 and 5'),
        ),
        migrations.AddConstraint(
            model_name='housing',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='Price must be a positive integer'),
        ),
    ]
