# Generated by Django 3.2.16 on 2022-11-26 16:58

from django.db import migrations

def move_housing_image(apps, schema_editor):
    Housing = apps.get_model('doogkingapp', 'Housing')
    HousingImage = apps.get_model('doogkingapp', 'HousingImage')

    for house in Housing.objects.all():
        image = HousingImage(housing=house, image=house.image, index=0)
        image.save()

def revert_move_housing_image(apps, schema_editor):
    HousingImage = apps.get_model('doogkingapp', 'HousingImage')
    HousingImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('doogkingapp', '0003_auto_20221126_1657'),
    ]

    operations = [
        migrations.RunPython(move_housing_image, revert_move_housing_image),
    ]
