# Generated by Django 3.2.16 on 2022-11-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doogkingapp', '0004_auto_20221126_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='image',
        ),
    ]
