# Generated by Django 3.2.16 on 2022-12-06 12:09

from django.db import migrations, models
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('doogkingapp', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default.svg', storage=storages.backends.azure_storage.AzureStorage, upload_to='profile/'),
        ),
    ]
