# Generated by Django 3.2.16 on 2022-12-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doogkingapp', '0008_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='housing',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
