# Generated by Django 3.2.16 on 2022-12-07 01:31

from django.db import migrations
from random import randint


def update_housing_ratings(apps, schema_editor):
    Housing = apps.get_model('doogkingapp', 'Housing')
    Reservation = apps.get_model('doogkingapp', 'Reservation')

    for house in Housing.objects.all():
        num_reservations = Reservation.objects.filter(
            housing__house_id=house.house_id
        ).count()
        if num_reservations > 0:
            house.rating = randint(0, 5) 
            house.num_ratings = randint(1, num_reservations)
        else:
            house.rating = 0
            house.num_ratings = 0
        house.save()


def revert_update_housing_ratings(apps, schema_editor):
    Housing = apps.get_model('doogkingapp', 'Housing')
    
    for house in Housing.objects.all():
        house.rating = 0
        house.num_ratings = 0
        house.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doogkingapp', '0009_auto_20221207_0129'),
    ]

    operations = [
        migrations.RunPython(
            update_housing_ratings,
            revert_update_housing_ratings
        )
    ]
