# Generated by Django 3.2.16 on 2022-12-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doogkingapp', '0011_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
