name: Regression tests
on:
  push:
    branches:
      - main
      - integration
  pull_request:
    branches:
      - main
      - integration
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 17
        cache: npm
        cache-dependency-path: '**/package-lock.json'

    - name: Installing npm requirements
      working-directory: ./frontend/
      run: npm install --force

    - name: Generate vue static files
      working-directory: ./frontend/
      run: npm run build

    - name: Upload artifacts to runner
      uses: actions/upload-artifact@v3
      with:
        name: vue_build
        path: ./frontend/dist/
    - name: Functional test housing
      run: |
        python3 manage.py test tests.test_housing_view
    - name: Functional tests header
      run: |
        python3 manage.py test tests.test_header
    - name: Functional tests footer
      run: |
        python3 manage.py test tests.test_footer
    - name: Functional tests my houses
      run: |
        python3 manage.py test tests.test_my_houses